---
- name: Remove directory structure
  win_file:
    path: C:\Users\ansible
    state: absent
 
- name: Create directory structure
  win_file:
    path: C:\Users\ansible
    state: directory
- name: Create Compliance Report
  win_command: cscc.exe -o Program Files\SCAP Compliance Checker 5.8\options.xml
  args:
    chdir: C:\Program Files\SCAP Compliance Checker 5.8

- name: Find files with .html
  win_find:   
    paths: C:\Users\ansible
    patterns: [ '*All-Settings_Windows*.html' ]
  register: file
- debug:
    msg:
  with_items:
       - "{{ file.files.0.filename }}"

- name: Copy files to EE
  ansible.builtin.fetch:
    src: "C:\\Users\\ansible\\{{ item }}"
    dest: "/tmp/{{ inventory_hostname }}/"
    flat: true
  loop:
    - "{{ file.files.0.filename }}"

- name: Copy folders to reports host
  ansible.builtin.copy:
    src: "/tmp/{{ inventory_hostname }}"
    dest: /home/awx/winreports/SCAP_Compliance_Checker
    mode: '0644'
  delegate_to: localhost
