---
- name: Build SCAP report Windows
  hosts: all      
  vars:
    Windows_firewall: "U_MS_Windows_Firewall_V2R1_STIG_SCAP_1-2_Benchmark.xml"
    Windows_2016: "U_MS_Windows_Server_2016_V2R3_STIG_SCAP_1-2_Benchmark.xml"
    Windows_2019: "U_MS_Windows_Server_2019_V2R3_STIG_SCAP_1-2_Benchmark.xml"

  roles:
    - run_scap_windows
