#- include_tasks: download_kb.yaml
#- include: download_kb.yaml
#- include: Install_hotfix.yaml
#  with_items:
#    - Windows8.1-KB3172729-x64.msu
#    - windows8.1-kb3019978-x64_80f7b7e16ab31192c6a75ab632db254df8c83a2e.msu
- name: Download hotfix  KB
  win_get_url:
    url: http://172.20.21.152:8080/win2012R2/{{ item }}
    dest: C:\{{ item }}
  with_items:
     - "{{ kb_list }}"
- name: Install hotfix no validating KB
  win_hotfix:
#    hotfix_kb: KB3172729
    source: C:\{{ item }}
    state: present
  with_items:
     - "{{ kb_list }}"
  register: hotfix_install

- ansible.windows.win_reboot:
  when: hotfix_install.reboot_required