- name: Create directory structure
  win_file:
    path: C:\Users\ansible\kb
    state: directory
- name: Download hotfix  KB
  win_get_url:
    url: http://172.20.21.153:8080/win2012R2/{{ item }}
    dest: C:\Users\ansible\kb\{{ item }}
  with_items:
     - "{{ kb_list }}"
- name: Install hotfix no validating KB
  win_hotfix:
#    hotfix_kb: KB3172729
    source: C:\Users\ansible\kb\{{ item }}
    state: present
  with_items:
     - "{{ kb_list }}"
  register: hotfix_install

#- ansible.windows.win_reboot:
#  when: hotfix_install.reboot_required