- include_tasks: item.yaml
- name: Download hotfix  KB
  win_get_url:
    url: http://172.20.21.152:8080/win2012R2/{{ item}}
    dest: C:\{{ item }}
#- name: Install hotfix validating KB
#  win_hotfix:
#    hotfix_kb: KB3172729
#    source: 
#      - C:\Windows8.1-KB3172729-x64.msu
#    state: present
#  register: hotfix_install
