---
#- include_tasks: download_kb.yaml
- include: download_kb.yaml
  with_items:
    - Windows8.1-KB3172729-x64.msu
    - windows8.1-kb3019978-x64_80f7b7e16ab31192c6a75ab632db254df8c83a2e.msu

#- name: Download hotfix  KB
#  win_get_url:
#    url: http://172.20.21.152:8080/win2012R2/{{ sites }}
#    dest: C:\{{ sites }}
#  loop: "{{ sites }}"
#  loop_control:
#    loop_var: site

#- name: Install hotfix validating KB
#  win_hotfix:
#    hotfix_kb: KB3172729
#    source: 
#      - C:\Windows8.1-KB3172729-x64.msu
#    state: present
#  register: hotfix_install
