- name: Retrieve Disk Usage
    win_shell: 'Get-PSDrive C | Select-Object Free'
    register: rawcsize

#  # Convert disk size in Gigabytes
  - name: Convert system disk into various formats and export
    vars:
      disk_out_free: '{{ rawcsize.stdout[0] }}'
      disk_int: '{{ rawcsize.stdout | int }}'
      disk_gb: '{{ disk_int | int}}'
    debug:
      msg: 'rawcsize.stdout: {{(rawcsize.stdout)}} disk_out_free: {{(disk_out_free)}}  disk_int: {{(disk_int)}} disk_gb: {{(disk_gb)}}'