- name: get disk free space
  win_shell: Get-PsDrive c | ConvertTo-Json
  register: output

- name: extract free space
  set_fact:
    free_json: "{{ output.stdout|from_json}}"

- name:
  debug:
    var: free_json.Free

- name: Gather disk facts
  win_disk_facts:

- name: Display disk free space
  debug:
    var: ansible_facts.win_disk_facts