- name: Check disk space on Windows
      block:
        - name: Check disk space on Windows
          win_shell: Get-Volume | Select-Object -Property DriveLetter, FileSystemLabel, FileSystem, SizeRemaining, Size | ConvertTo-Csv -NoTypeInformation
          register: windows_disk_space
        - name: Print disk space on Windows
          debug:
            msg: "{{ windows_disk_space.stdout_lines }}"
        - name: Write disk space to CSV file on Windows
          local_action:
            module: copy
            content: "{{ windows_disk_space.stdout }}"
            dest: "{{ inventory_hostname }}-disk-space.csv"
      when: ansible_os_family == 'Windows'