- name: 'Check free space in C:'
  win_shell: 'write-host ([math]::Round((Get-PSDrive C | Select-Object Free).free / 1024 / 1024 / 1024,2))'
  register: freespace

- name: report free disk space
  debug:
    msg: |
      "{{ freespace.stdout }} GB"